version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: watchlist-hub_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=watchlist-hub
    volumes:
      - watchlist-hub_pg_data:/bitnami/postgresql
  redis:
    image: bitnami/redis:latest
    container_name: watchlist-hub_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'watchlist-hub_redis_data:/bitnami/redis/data'
volumes:
  watchlist-hub_pg_data:
  watchlist-hub_redis_data:
