version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: watchlist-hub_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=watchlist-hub
    volumes:
      - watchlist-hub_pg_data:/bitnami/postgresql
volumes:
  watchlist-hub_pg_data:
